---
micronaut:
  application:
    name: micronaut-kafka-avro-v2

---
kafka:
  bootstrap:
    servers: localhost:9092
  schema:
    registry:
      url: http://localhost:8081
  streams:
    default:
      application.id: partner-v2
      processing.guarantee: exactly_once

graphql-factory-config:
  classpath: classpath:schema.graphqls
  schema:
    - Mutation

topics:
  partnerTopic: partner-topic

---
graphql:
  enabled: true
  graphiql:
    enabled: true
    path: /graphiql